name: Testing CI

on: push

jobs:
  super-lint-Unittest:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my code
        uses: actions/checkout@v3

      - name: Run Super-Lint
        uses: github/super-linter@v5
        env:
            VALIDATE_ALL_CODEBASE: false
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Unit-testing
        run: python test_cases.py
  
  Publish:
    name: Create Docker Image and push
    runs-on: ubuntu-latest
    needs: super-lint-Unittest
    steps:
      - name: Create Docker Image and push
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: smssajadi/se-docker-repository
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD}}
    